# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-EasyDBI
version:      1.13
version_from: lib/POE/Component/EasyDBI.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           1.38
    Error:                         0.15
    POE:                           0.20

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
